name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # - name: Build - no need of build as the assumption is that we have already built the project
      # run: cargo build --release

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: releases/production/readme.md
        asset_name: mything
        tag: ${{ github.ref }}
        overwrite: true
        body: "hey! I just released a MD file.  Hope you like it."